package GUI;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Rober
 */
public class VAddODeleteAmigoAPandilla extends javax.swing.JFrame {

    PPrincipal p;
    int cod;
    String nombre;
    boolean añadir;

    public VAddODeleteAmigoAPandilla(PPrincipal p, int cod, String nombre, boolean añadir) {
        this.p = p;
        this.cod = cod;
        this.nombre = nombre;
        this.añadir = añadir;
        initComponents();
        minitComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bCancelar = new javax.swing.JButton();
        bAddDelete = new javax.swing.JButton();
        etiquetaNombre = new javax.swing.JLabel();
        comboPandillas = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre Amigo");

        jLabel3.setText("Nombre Pandilla");

        bCancelar.setText("Cancelar");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        bAddDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddDeleteActionPerformed(evt);
            }
        });

        etiquetaNombre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        comboPandillas.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(50, 50, 50))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(56, 56, 56)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboPandillas, 0, 135, Short.MAX_VALUE)
                            .addComponent(etiquetaNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addComponent(bAddDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboPandillas, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bAddDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAddDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddDeleteActionPerformed
        ResultSet rs=null;
        int codPandilla=0;
        String nombrePandilla=(String)comboPandillas.getSelectedItem();
        if (añadir) {
            try {
                //hacemos esta consulta para saber si este amigo existe en la pandilla
                rs=p.gb.buscarAmigoPorPandilla(nombre,nombrePandilla);
                if(rs.next()){
                    JOptionPane.showMessageDialog(this,"Ya existe este amigo en esa pandilla.");
                }else{
                  codPandilla=p.gb.consultarPandillasPorNombre(nombrePandilla);
                  p.gb.agregarAmigoAPandilla(cod, codPandilla);
                  JOptionPane.showMessageDialog(this,"Has añadido a "+nombre+" a la pandilla "+nombrePandilla);
                  this.dispose();
                }
            } catch (SQLException ex) {
                Logger.getLogger(VAddODeleteAmigoAPandilla.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            codPandilla=p.gb.consultarPandillasPorNombre(nombrePandilla);
            if(JOptionPane.showConfirmDialog(this,"¿Quieres eliminar a "+nombre+" de la pandilla "+nombrePandilla+"?","¿?",JOptionPane.YES_NO_OPTION)==0){
            p.gb.borrarAmigodePandilla(cod, codPandilla);
            this.dispose();
            }
        }

    }//GEN-LAST:event_bAddDeleteActionPerformed

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_bCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAddDelete;
    private javax.swing.JButton bCancelar;
    private javax.swing.JComboBox<String> comboPandillas;
    private javax.swing.JLabel etiquetaNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void minitComponents() {

        this.setLocationRelativeTo(p.v);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        cargarCombo();
        etiquetaNombre.setText(nombre);
        if (añadir) {
            this.setTitle("Añadir amigo a pandilla");
            bAddDelete.setText("Añadir");
        } else {
            this.setTitle("Eliminar amigo de pandilla");
            bAddDelete.setText("Eliminar");
        }
        this.setResizable(false);
    }

    public void cargarCombo() {
        ResultSet rs;
        if (añadir) {
            try {
                rs = p.gb.consultarPandillas();
                while (rs.next()) {
                    comboPandillas.addItem(rs.getString(2));
                }
            } catch (SQLException ex) {
                Logger.getLogger(VAddODeleteAmigoAPandilla.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            try {
                rs = p.gb.pandillasDeUnAmigo(cod);
                while (rs.next()) {
                    comboPandillas.addItem(rs.getString(1));
                }
            } catch (SQLException ex) {
                Logger.getLogger(VAddODeleteAmigoAPandilla.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }
}
